// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using abfi_weighing_scale_api.Data;

#nullable disable

namespace abfi_weighing_scale_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215061237_addedNewDbTblForBookingsFeatures")]
    partial class addedNewDbTblForBookingsFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate")
                        .HasDatabaseName("IX_Bookings_BookingDate");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.BookingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductClassificationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductClassificationId");

                    b.HasIndex("BookingId", "CustomerId", "ProductClassificationId")
                        .IsUnique()
                        .HasDatabaseName("UX_BookingItems_Booking_Customer_Product");

                    b.ToTable("BookingItems", (string)null);
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("IX_Customers_CustomerName");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Farms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("FarmName")
                        .IsUnique()
                        .HasDatabaseName("IX_Farms_FarmName");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Farms_IsActive");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.ProductClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CratesWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("IndividualWeightRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NoOfHeadsPerGalantina")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TotalWeightRangePerCrate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ProductClassification_IsActive");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("IX_ProductClassification_ProductCode");

                    b.ToTable("ProductClassification", (string)null);
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("TotalHeads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Production_CreatedAt");

                    b.HasIndex("EndDateTime")
                        .HasDatabaseName("IX_Production_EndDateTime");

                    b.HasIndex("ProductionName")
                        .HasDatabaseName("IX_Production_ProductionName");

                    b.HasIndex("StartDateTime")
                        .HasDatabaseName("IX_Production_StartDateTime");

                    b.ToTable("Production");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.ProductionFarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllocatedHeads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int?>("ForecastedTrips")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ProductionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FarmId")
                        .HasDatabaseName("IX_ProductionFarm_FarmId");

                    b.HasIndex("ProductionId")
                        .HasDatabaseName("IX_ProductionFarm_ProductionId");

                    b.HasIndex("ProductionId", "FarmId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProductionFarm_ProductionId_FarmId");

                    b.ToTable("ProductionFarms");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.BookingItem", b =>
                {
                    b.HasOne("abfi_weighing_scale_api.Models.Entities.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("abfi_weighing_scale_api.Models.Entities.Customer", "Customer")
                        .WithMany("BookingItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("abfi_weighing_scale_api.Models.Entities.ProductClassification", "ProductClassification")
                        .WithMany("BookingItems")
                        .HasForeignKey("ProductClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("ProductClassification");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.ProductionFarm", b =>
                {
                    b.HasOne("abfi_weighing_scale_api.Models.Entities.Farms", "Farm")
                        .WithMany("ProductionFarms")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("abfi_weighing_scale_api.Models.Entities.Production", "Production")
                        .WithMany("ProductionFarms")
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Production");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Booking", b =>
                {
                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Customer", b =>
                {
                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Farms", b =>
                {
                    b.Navigation("ProductionFarms");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.ProductClassification", b =>
                {
                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("abfi_weighing_scale_api.Models.Entities.Production", b =>
                {
                    b.Navigation("ProductionFarms");
                });
#pragma warning restore 612, 618
        }
    }
}
